name: Main workflow

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: manferlo81/reusable-workflow-test/.github/workflows/reusable.yml@main

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
