name: Main workflow

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
